version: '2'
services:
  mysqldata:
    image: busybox
    container_name: docker-mysqldata
    volumes:
     - /var/lib/mysql
  mysql:
    image: mysql
    container_name: docker-mysql
    stdin_open: true
    tty: false
    ports:
      - "33060:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: phpdata
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes_from:
      - mysqldata
  php:
    build: ./php
    container_name: docker-php
    stdin_open: true
    tty: false
    ports:
      - '8080:80'
    volumes:
      - ./src:/var/www/html
      - ./apache:/etc/apache2/sites-enabled/
    depends_on:
      - mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8081:80'
    links:
      - mysql:db
    environment:
      PMA_USER: root
      PMA_PASSWORD: password
    depends_on:
      - mysql
      - php
